server:
  port: '8080'
spring:
  application:
    name: ewm-main-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/main_db'
    username: main
    password: main
app:
  client:
    url: 'http://localhost:9090'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        transaction:
          interceptor: TRACE
        web: DEBUG
      apache:
        http:
          wire=DEBUG:
