CREATE TABLE IF NOT EXISTS users
(
    userId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email  VARCHAR(254) NOT NULL UNIQUE,
    name   VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    categoryId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    eventId            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         varchar(2000) NOT NULL,
    categoryId         BIGINT        NOT NULL references categories (categoryId),
    confirmed_requests int,
    created_on         timestamp     NOT NULL,
    published_on       timestamp,
    description        varchar(7000) NOT NULL,
    event_date         timestamp     NOT NULL,
    initiatorId        BIGINT        NOT NULL references users (userId),
    paid               BOOLEAN       NOT NULL,
    participant_limit  int,
    state              varchar(50)   NOT NULL,
    request_moderation BOOLEAN,
    title              varchar(120)  NOT NULL,
    lat                FLOAT         NOT NULL,
    lon                FLOAT         NOT NULL,
    views              BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    requestId   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventId     BIGINT                      NOT NULL references events (eventId),
    requesterId BIGINT                      NOT NULL references users (userId),
    created     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status      VARCHAR(50)                 NOT NULL,
    CONSTRAINT UQ_PARTICIPANT_PER_EVENT UNIQUE (requesterId, eventId)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilationId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned        BOOLEAN     NOT NULL,
    title         VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilationId BIGINT NOT NULL REFERENCES compilations (compilationId) ON DELETE CASCADE,
    eventId       BIGINT NOT NULL REFERENCES events (eventId) ON DELETE CASCADE,
    PRIMARY KEY (compilationId, eventId)
);

create table if not exists likes
(
    likeId     bigint generated by default as identity primary key,
    entityType varchar(50),
    entityId   bigint,
    value      bigint,
    createdAt  timestamp,
    userId     bigint,
    message    text,
    updatedAt  timestamp
);


create unique index if not exists likes_entity_id_entity_type_user_id_uindex
    on likes (entityId, entityType, userId);

create or replace view rating_likes(entity_type, entity_id, sum) as
SELECT entityType,
       entityId,
       sum(value) AS total
FROM likes
GROUP BY entityType, entityId;



